[package]
name = "repocat"
version = "0.5.0"
edition = "2021"
description = "A tool to concatenate all code and text files in a github repo for LLM inference contexts"
repository = "https://github.com/SamKG/repocat"
license = "MIT"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
ignore = "0.4.25"
glob = "0.3.3"
base64 = "0.22.1"

[features]
default = []
